server:
  port: 9090
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sanmedi27/config-data
          default-label: main
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}